spring:
  application:
    name: TodoApplication
  datasource:
    url: jdbc:postgresql://localhost:2025/todo_db
    username: seth
    password: kuasi7
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 7070
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health, info, mappings, beans
  info:
    env:
      enabled: true

info:
  app:
    name: TodoApplication
    version: 0.0.1-SNAPSHOT
    description: A simple todo application that allows users to create, read, update and delete their todos
    developers:
      - Seth Ofosu Okyere - seth.okyere@amalitechtraining.org